export const WARHAMMER_FANTASY_ROLEPLAY_FIRST_EDITION = {};

/**
 * The set of Ability Scores used within the system.
 * @type {Object}
 */
WARHAMMER_FANTASY_ROLEPLAY_FIRST_EDITION.abilities = {
  str: 'WARHAMMER_FANTASY_ROLEPLAY_FIRST_EDITION.Ability.Str.long',
  dex: 'WARHAMMER_FANTASY_ROLEPLAY_FIRST_EDITION.Ability.Dex.long',
  con: 'WARHAMMER_FANTASY_ROLEPLAY_FIRST_EDITION.Ability.Con.long',
  int: 'WARHAMMER_FANTASY_ROLEPLAY_FIRST_EDITION.Ability.Int.long',
  wis: 'WARHAMMER_FANTASY_ROLEPLAY_FIRST_EDITION.Ability.Wis.long',
  cha: 'WARHAMMER_FANTASY_ROLEPLAY_FIRST_EDITION.Ability.Cha.long',
};

WARHAMMER_FANTASY_ROLEPLAY_FIRST_EDITION.abilityAbbreviations = {
  str: 'WARHAMMER_FANTASY_ROLEPLAY_FIRST_EDITION.Ability.Str.abbr',
  dex: 'WARHAMMER_FANTASY_ROLEPLAY_FIRST_EDITION.Ability.Dex.abbr',
  con: 'WARHAMMER_FANTASY_ROLEPLAY_FIRST_EDITION.Ability.Con.abbr',
  int: 'WARHAMMER_FANTASY_ROLEPLAY_FIRST_EDITION.Ability.Int.abbr',
  wis: 'WARHAMMER_FANTASY_ROLEPLAY_FIRST_EDITION.Ability.Wis.abbr',
  cha: 'WARHAMMER_FANTASY_ROLEPLAY_FIRST_EDITION.Ability.Cha.abbr',
};
